### ISSUE TITLE
discord forcing phone verification

### ISSUE THREAD

**Issue by truedruid** [cedws/discord-delete#10]
partial 
WARNING:root:Server sent Forbidden

**Comment by truedruid** [comment]
full -p

WARNING:root:Server sent Forbidden.
INFO:root:	[insert msg number]

at some point after during partial deletion, after a ran full deletion overnight (which didnt delete everything but deleted a lot)

**Comment by cedws** [comment]
As long as you pass a token from a session with your phone number verified (you can do this through the browser), the script will work correctly. That probably isn't the source of the `Forbidden` warning you're seeing here.
I've been investigating a problem with full deletion behind the scenes. I'm not sure whether Discord changed their API or not, but the script doesn't seem to be able to delete messages in servers that a user isn't participating in anymore, hence the `Forbidden`. The user doesn't have permission to delete such messages once they've left the server. This is something I'm sure worked a while ago. For now, I can only recommend running a partial deletion and keeping your account open just in case I find a new way of achieving full deletion.
I will update the README shortly to rectify any misleading information.

**Comment by cedws** [comment]
Closing - if you have any more issues, please reopen.
