### ISSUE TITLE
Looking for assistance, would like to use this but I have zero understanding how.

### ISSUE THREAD

**Issue by ghost** [cedws/discord-delete#12]
I would like to delete my discord messages with your program, however I have **zero** understanding regarding which dependencies and programs I need or how to use them. If you could provide me any information on how to successfully install your program I would greatly appreciate it.
Thank you

**Comment by cedws** [comment]
I can't really hold your hand through it, but I can point you in the right direction.

You're probably on Windows, so you'll need to download Python from [here](https://www.python.org/downloads/windows/). That should install `pip` too IIRC. Make sure to tick `Add to PATH` (paraphrasing) in the installer.

Then you can open your shell of choice (PowerShell/CMD) and follow the [guide](https://github.com/c-edw/discord-delete/wiki) for a full or partial deletion.

Failing that, I'm sure somebody in the Python community would be willing to help you out.

**Comment by ghost** [comment]
Got it working, thank you so much for your work making this program and helping me, I really do appreciate it.
