### ISSUE TITLE
Feature Request: Overwrite messages N times before (optionally) deleting

### ISSUE THREAD

**Issue by discordprivacy** [cedws/discord-delete#13]
Instead of merely deleting messages, they should first be overwritten N times. The data with which to overwrite the messages should be no shorter in length than that which it replaces and either randomly generated or user-configurable, repeating if necessary to meet the length requirement.

### Rationale
There is a very good possibility that when a request to delete a message is made, Discord simply marks that message as deleted and retains the actual message content. By overwriting the message first, we reduce the risk of the message content being retained.

Of course, this measure will fail to achieve our goal if Discord saves the complete edit history. But there is little we can do in that event.

**Comment by discordprivacy** [comment]
Ideally, we would have a custom client or mod which would replace all outgoing messages with random strings, only to immediately restore the original message's content. 

Why? Because Discord might retain the initial message content, and maybe the final message state, but perhaps not the intermediate states.

Process would be thus
1. User types a message (ex. "hello") in message box and hits send
2. Our custom client/mod intervenes, saves the message "hello" for later and sends a random string instead
3. The custom client/mod then immediately issues a request to replace the content of the message with the actual user-specified content, ("hello" in this example).

Additionally, after step 2 the message could be overwritten N times with random data, in case Discord saves first N edits of a message.

A more user-friendly placeholder like "message loading" could be sent in place of random data.

The user could also have the option to have his messages 'self-destruct' after a given length of time has elapsed.

Once again, all these measures will fail if Discord retains full message history, or uses some kind of heuristic like "retain first message which persists for more than 1 minute", or keeps full database backups, or shares data with third parties (e.g. SPLC), &c.

**Comment by cedws** [comment]
You have some very good ideas. I did have a message overwrite feature kind of implemented at one point, but removed it. Discord are obliged to delete those messages within a certain time period on the user's request under the GDPR, and I rely on them doing that.

Sadly, I don't think we'll ever find out if Discord *really do* delete messages, or whether they store full edit history. It's for reasons like this that I recommend people avoid Discord completely if possible. Even with the most clever scripts and tools, you can't really protect your privacy. It's the next generation Facebook.

**Comment by aaronjanse** [comment]
> There is a very good possibility that when a request to delete a message is made, Discord simply marks that message as deleted and retains the actual message content. By overwriting the message first, we reduce the risk of the message content being retained.

> Discord are obliged to delete those messages within a certain time period on the user's request under the GDPR, and I rely on them doing that.

I think that Discord is already generously allowing database-intensive scripts like these to run. I'm worried that going too far could get users banned. Maybe one rewrite, max.

**Comment by cedws** [comment]
Yep, luckily they haven't banned any of my accounts (or anyone else's to my knowledge) for using a tool like this, but I don't want to push my luck.
Closing.
