### ISSUE TITLE
pushing version that allows (white or black)listing servers to not delete and giving the token in the command line directly

### ISSUE THREAD

**Issue by ghost** [cedws/discord-delete#14]
hello, sorry this isn't really an issue i really do not know how to use this site. i made a couple changes to the script to suit my needs, choosing what servers not to delete messages on and providing my discord token in the command prompt directly instead of registering a powershell symbol or whatever, and i was wondering if that could interest you. the code added is kinda messy garbage but it does the job and should still work under linux. 

thanks so much for making this and i hope you come across a solution to the full deletion 403 problem (thought i doubt it's in your hands)

**Comment by cedws** [comment]
Hello, I would be interested in having a look to see whether we can cherry pick some of the changes. Are you able to send a pull request? As for the 403 problem, as you say, it's sadly not in my hands. It's solely in Discord's hands, because it's a restriction in their API. I've been thinking of various ways around it, but none of them solve the root problem.

Thanks for your interest.

**Comment by ghost** [comment]
sorry for the late reply i would have thought github notified me. i don't seem to be able to create a pull request so here's the python file, use a diff checker to see what i added (or deleted)
[discord_delete.txt](https://github.com/c-edw/discord-delete/files/3242302/discord_delete.txt)

one thing i noticed is the dm channels ids aren't in the url like regular servers so you need to be careful if you want to keep some dms.

**Comment by cedws** [comment]
Thanks for sending your changes over. I considered using your code to add a token argument, but usually this is considered bad security practice. Tokens/secrets should ideally always be passed as environment variables. As for the blacklist, it would do the job, but not everybody is capable of finding the channel IDs for themselves.
