### ISSUE TITLE
Rebuild this tool to be user-friendly (extension/GUI application?)

### ISSUE THREAD

**Issue by cedws** [cedws/discord-delete#16]
It's evident that a portion of users of this tool aren't developers and often struggle to get it working, which I can completely understand. Having to install Python and the modules is a pain if you don't know what you're doing.

I'm considering rebuilding the tool in a compiled language, and including a GUI to make it easy to use. I'm not sure how I'll do this. My go-to language would be Rust, but it doesn't have any strong GUI libraries currently.

**Comment by cedws** [comment]
Another random thought: since full deletion isn't really effective anymore, this whole thing could probably be done as a browser extension...

**Comment by cedws** [comment]
More thoughts on the extension. Discord has maliciously cut off access to localStorage, preventing access to the auth cookie (this is absolutely insane and only reinforces my statement in the README...).
Thankfully, a clever guy has found [a way around it](https://github.com/FOCI-DEV/Get-Discord-Token). I'll probably use this as a starting point. Though I have no doubts Discord will make things even more difficult in future. Insane.

**Comment by larryqiann** [comment]
In my experience I've found that getting this running on a Mac running the latest macOS (Mojave) requires:
-Homebrew
-Clone the repo
-brew install python3
-pip3 install aiohttp
-DISCORD_TOKEN=[token] python3 discord_delete.py -v partial

Perhaps in the meantime this could be added to a readme or other file to help other users.

**Comment by cedws** [comment]
@larryqiann 
Thanks, you highlighted some good improvements to the wiki pages here which have been added. Most importantly, I forgot to mention to install Python...
Rather than `pip3 install aiohttp`, you can use `pip3 install -r requirements.txt` to ensure you get all of the dependencies that the project requires. Just for future reference.

**Comment by larryqiann** [comment]
Another thing I noticed is that the whitelisting/blacklisting nomenclature may benefit from further explanation. Many browser extensions use "whitelist" to refer to "avoid processing these items". When I tested it, it appeared that the opposite was true for this.

**Comment by zyrodos** [comment]
Yeah, this would be super helpful. I've been trying to run this for the past few days and am constantly running into errors.

**Comment by cedws** [comment]
You're welcome to raise issues for the problems you are encountering. I may rewrite the tool soon if I get the time.

**Comment by cedws** [comment]
Update for those interested: I am rewriting this project in Go on the `GoRewrite` branch. I wouldn't recommend using it yet though - I'll make a release and distribution archives when the time comes.

**Comment by zyrodos** [comment]
Hi,

So I download delete-discord-windows file which is 9.23 MB, not the zip, correct (version 1.1.2)?

After that, I put the file on a place like my desktop and then open powershell. Then I get my auth key, which I believe I am doing correctly, and putting it in between the parenthesis `$env:DISCORD_TOKEN="[YOUR TOKEN]"` where `[YOUR TOKEN]` would be.

Then I click enter?

Then I copy and paste `./discord-delete-windows partial` into powershell and click enter, but when I do this, I run into various errors.

Can you please help me figure out where I am going wrong @c-edw? Thank you

**Comment by cedws** [comment]
@zyrodos I would be happy to. Can you post the output of `./discord-delete-windows -v partial`? Be sure to redact your token and any numeric IDs (`123456789`) from the output.

**Comment by zyrodos** [comment]
@c-edw 

./discord-delete-windows : The term './discord-delete-windows' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At line:1 char:1
+ ./discord-delete-windows partial
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (./discord-delete-windows:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by cedws** [comment]
@zyrodos The command that you're pasting into PowerShell references a program (`discord-delete-windows`). See the `./` at the start of the command? That means that you're asking PowerShell to look in the current directory for the program. If the program isn't there, that's what would cause the error that you've pasted above.

I assume that you saved `discord-delete-windows` to your `Downloads` folder. Try running `cd ~/Downloads` in PowerShell, then run `./discord-delete-windows -v partial` after that (and don't forget to set the token too first - `$env:DISCORD_TOKEN="[YOUR TOKEN]"`).

**Comment by zyrodos** [comment]
Hey thanks @c-edw I did that, but ran into this error message:

Program 'discord-delete-windows' failed to run: No application is associated with the specified file for this
operationAt line:1 char:1
+ ./discord-delete-windows -v partial
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ ./discord-delete-windows -v partial
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

**Comment by cedws** [comment]
Hey @zyrodos, I was able to reproduce your issue on my machine and I've created a new release to fix this. Please download the new binary (`discord-delete-windows.exe`) and follow the same steps as before.
```
cd ~/Downloads
$env:DISCORD_TOKEN="[YOUR TOKEN]"
./discord-delete-windows.exe -v partial
```

**Comment by zyrodos** [comment]
Thanks, I tried it and got an error:

time="2019-10-27T19:40:29-04:00" level=debug msg="DELETE https://discordapp.com/api/v6/channels/numberstringhere912349324/messages/numberstringhere912349324"
time="2019-10-27T19:40:29-04:00" level=debug msg="Server returned status Too Many Requests"
time="2019-10-27T19:40:29-04:00" level=info msg="Server asked us to sleep for 449 milliseconds"
time="2019-10-27T19:40:30-04:00" level=debug msg="DELETE https://discordapp.com/api/v6/channels/275617516783665152/messages/600475494772899909"
time="2019-10-27T19:40:30-04:00" level=debug msg="Server returned status No Content"
time="2019-10-27T19:40:30-04:00" level=debug msg="Skipping context message"
time="2019-10-27T19:40:30-04:00" level=debug msg="Skipping context message"
time="2019-10-27T19:40:30-04:00" level=info msg="Deleting message numberstringhere912349324 from numberstringhere912349324"
time="2019-10-27T19:40:30-04:00" level=debug msg="DELETE https://discordapp.com/api/v6/channels/numberstringhere912349324/messages/numberstringhere912349324"
time="2019-10-27T19:40:30-04:00" level=debug msg="Server returned status No Content"
time="2019-10-27T19:40:30-04:00" level=debug msg="Skipping context message"
time="2019-10-27T19:40:30-04:00" level=debug msg="Skipping context message"
time="2019-10-27T19:40:30-04:00" level=info msg="Deleting message numberstringhere912349324 from channel numberstringhere912349324"
time="2019-10-27T19:40:30-04:00" level=debug msg="DELETE https://discordapp.com/api/v6/channels/numberstringhere912349324/messages/numberstringhere912349324"

and it keeps repeating

I replaced the string of numbers that would signify the channel and the server with "randomstringhere912349324"

any idea?

**Comment by cedws** [comment]
@zyrodos It looks like it's working. You'll need to give it some time to finish. Run the command without `-v` and it will give you a better idea of what's going on.

**Comment by zyrodos** [comment]
@c-edw you're the best, thank you for walking me through this. i truly appreciate it, it is running now!

**Comment by zyrodos** [comment]
Hi, I just realized there were some servers and DM convos that it doesn't fully delete things from anymore on Windows. Have you noticed this with other users? @cedws ?

**Comment by cedws** [comment]
> Hi, I just realized there were some servers and DM convos that it doesn't fully delete things from anymore on Windows. Have you noticed this with other users? @cedws ?

@larryqiann has also reported this. If it started happening suddenly to multiple people then there's a chance that Discord have updated their API. I will try to take a look tomorrow.

When do you last remember it working?

**Comment by zyrodos** [comment]
Hey, I think I remember it last working maybe a week(ish) ago? Right now it deletes just some stuff from some channels and seems to skip over a bunch of stuff seemingly at random. Thanks @cedws

**Comment by cedws** [comment]
Hello @zyrodos, a new release has been made with a change that might resolve your issue. Please give this a go. Let's discuss any further deletion problems in #21.
