### ISSUE TITLE
Delete From Only One Channel?

### ISSUE THREAD

**Issue by Errora403** [cedws/discord-delete#17]
How can I use this script to delete messages from **one specific server channel only**?

**Comment by cedws** [comment]
There's no functionality to do this in the tool, since it would require finding various IDs which wouldn't be user friendly. There is a way you could do this though. If you follow the instructions for a full deletion, but delete the files (from the data archive) which contain messages from other channels, it will delete only the ones you leave behind.
I'm planning to build a browser extension to delete messages, and it will probably include the ability to delete messages from particular channels.

**Comment by Errora403** [comment]
Can I find the specific channel folder, ZIP it and refer to it when executing that command?

**Comment by cedws** [comment]
Sorry, yes, I forgot that it will automatically extract the ZIP. As long as you retain the same structure of files when you ZIP it back up, it will delete from the channels left behind as you want it to.

**Comment by Errora403** [comment]
Just to clarify, can I move a specific channel folder to a different location, and ZIP only that one folder? Will that work to delete messages from only that channel?

![bilde](https://user-images.githubusercontent.com/23483786/59200324-3f9c2b80-8b98-11e9-9dd2-2fec23a34bfa.png)

![bilde](https://user-images.githubusercontent.com/23483786/59200330-41fe8580-8b98-11e9-927c-759a406946bc.png)

**Comment by cedws** [comment]
You can do that, but you need to retain the original structure of the ZIP file. So you'll need to have a `messages` directory inside, and then that should contain a numbered folder containing `channel.json` and `messages.csv`.

**Comment by cedws** [comment]
Yeah, this is stupid, sorry. I'm going to add basic whitelist/blacklist parameters for this use case.

**Comment by cedws** [comment]
If you get the new version of the script now, you can use `-w`/`--whitelist` and specify the ID you've found here. That'll ensure only messages are deleted from that channel. Your command will look something like:
`./discord-delete.py full -p [PATH] -w 276837249075773460`

**Comment by Errora403** [comment]
Wow. This is awesome. Thank you.

**Comment by ylluminarious** [comment]
@cedws Does this whitelist feature still work in the new Go implementation? I tried to use it, but it says: `Error: unknown flag: --whitelist`

**Comment by cedws** [comment]
> @cedws Does this whitelist feature still work in the new Go implementation? I tried to use it, but it says: `Error: unknown flag: --whitelist`

Hey. Sorry, the Go version doesn't have this feature. You can still get the Python version from Releases or the `PythonImpl` branch, not sure if it still works.

**Comment by ylluminarious** [comment]
@cedws Okay, thanks for letting me know. I ended up using this tool instead: https://github.com/victornpb/deleteDiscordMessages

It would still be nice to have a CLI version, though. So I hope you'll consider re-adding this feature to the Go implementation 🙂
