### ISSUE TITLE
eindows.exe file is not recognized.

### ISSUE THREAD

**Issue by Spade1953** [cedws/discord-delete#23]
I am using windows, I have verified my token is correct, and I am using PowerShell to use the commands. 

The error message is: /discord-delete-windows.exe : The term '/discord-delete-windows.exe' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At line:1 char:1
+ /discord-delete-windows.exe partial
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (/discord-delete-windows.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by cedws** [comment]
You need to `cd` to the folder where you downloaded the program. Run `cd ~/Downloads` to move to your Downloads folder. Then run `./discord-delete-windows.exe partial` (note the `.` at the start, this is important).

**Comment by Spade1953** [comment]
Thank you! It worked.
