### ISSUE TITLE
Unable to run the latest release on Ubuntu Desktop 20.04.1

### ISSUE THREAD

**Issue by ghost** [cedws/discord-delete#24]
Hello. I'm trying to run this app on my Ubuntu Desktop machine. It is a fully up-to-date install of Ubuntu Desktop 20.04.1. When I attempt to run the app I am thrown this error message: ``./discord-delete-linux: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./discord-delete-linux)``.

**Comment by cedws** [comment]
Hey, thanks for your report. I forgot to enable static linking. Could you try 1.2.6 which was just released?

**Comment by ghost** [comment]
> Hey, thanks for your report. I forgot to enable static linking. Could you try 1.2.6 which was just released?

It's working now, thanks!
