### ISSUE TITLE
Feature request: skip servers/channels

### ISSUE THREAD

**Issue by ghost** [cedws/discord-delete#26]
**Request:**
Please may a feature be added to skip inputted servers and channels? For example if I wanted to skip deletion of messages in my favourite server I would add the argument `-skip "https://discord.com/channels/896848632576878238"` or `-skip "896848632576878238"`, `896848632576878238` being the ID of the server located in the address bar. Ideally the same argument could be used to only skip specific channels for example if I wanted to skip my PMs to my best friend I would add the argument `-skip "https://discord.com/channels/@me/239683589746734632"` or `-skip "@me/239683589746734632"`. If I wanted to skip a single channel in a server instead of skipping the whole server I could use the argument `-skip "https://discord.com/channels/435695963835744643/746945884567556432"` or `-skip "435695963835744643/746945884567556432"`. Another ideality would be the ability to add multiple servers and channels to the same argument, for example if I wanted to skip my favourite server and my PMs to my best friend I would use the command `-skip "https://discord.com/channels/896848632576878238" "https://discord.com/channels/@me/239683589746734632"` or `-skip "896848632576878238" "@me/239683589746734632"`.

Thanks for making this awesome tool! It saves me a lot of time and I'm a big fan of automation. If this feature request is unable to be fulfilled that is okay, if I was able to do it myself I would however I'm not a programmer.

**Conclusion:**

- [ ] Add the ability to skip an entire server by using the CLI argument `-skip "https://discord.com/channels/[server ID]"` or `-skip "[server ID]"`
- [ ] Add the ability to skip an entire server channel by using the CLI argument `-skip "https://discord.com/channels/[server ID]/[channel ID]"` or `-skip "[server ID]/[channel ID]"`
- [ ] Add the ability to skip entire channel by using the CLI argument `-skip "https://discord.com/channels/@me/[channel ID]"` or `-skip "@me/[channel ID]"`
- [ ] Add the ability to use all of the above CLI argument values in one argument for example: `-skip "https://discord.com/channels/[server ID]" "https://discord.com/channels/[server ID]/[channel ID]" "https://discord.com/channels/@me/[channel ID]"` or `-skip "[server ID]" "[server ID]/[channel ID]" "@me/[channel ID]"`

**Comment by cedws** [comment]
There's been a lot of requests for this, so maybe it's time. I'll see when I can get around to it.
