### ISSUE TITLE
EOF error after running it for a while

### ISSUE THREAD

**Issue by beranos** [cedws/discord-delete#28]
as the title says i get an error when the program runs for 15-20 mins+ (maybe its just for me) and this is the 2 time happening in an hour maybe. this is the error i got in the console:

time="2021-01-15T03:50:31+01:00" level=fatal msg="Error deleting message: Error sending request: Delete \"https://discord.com/api/v6/channels/censored/messages/censored\": unexpected EOF"

obviously the program exits after i get that

**Comment by cedws** [comment]
This looks like an issue on the server side, not sure if there is anything that can be done.

**Comment by cedws** [comment]
Closing since there are no updates and this is a server-side or network problem.
