### ISSUE TITLE
Bans

### ISSUE THREAD

**Issue by ItsCinnabar** [cedws/discord-delete#32]
I have used this application for almost 2 years now, and up until a month ago it was without being banned. In the last month I have been banned twice. Both times were within hours of running the program. Seems discord upd their game and decided to start caring?

**Comment by cedws** [comment]
I haven't seen anything that suggests they're cracking down. Discord has a bad policy of banning (potentially innocent) users who participate in rulebreaking servers, or users who are friends of rulebreakers. It's possible that you fit into one of these categories, or a heavy handed ML algorithm banned you.

Maybe you could ask support about the reason for your bans, but they may not tell you why. If you find anything out, let me know.

**Comment by cedws** [comment]
I can vouch for this now. Had an account banned for self botting today. This likely applies to all deletion tools.
I think more stark warnings are going to be needed for potential users of this.

**Comment by cedws** [comment]
Closing in favor of #33
