### ISSUE TITLE
Not all messages are being delete

### ISSUE THREAD

**Issue by ghost** [cedws/discord-delete#36]
Hello. I've tried using this tool as usual over the past week however it is not deleting all messages. I cannot seem to find anything in common with the messages it doesn't delete however I have plenty left over.

This didn't happen before. I've tried using both the Windows and Linux client and I'm still experiencing the issue.

**Comment by cedws** [comment]
Need more information, what version are you using, what parameters? Is the program exiting with an error?

**Comment by ghost** [comment]
> 
> 
> Need more information, what version are you using, what parameters? Is the program exiting with an error?

I found the common denominator. Every channel that has messages left over in it gets this debug message `Found message of non-zero type, incrementing seek index`

**Comment by ghost** [comment]
Going back to version version 1.3.1 resolved these issues

**Comment by cedws** [comment]
This helps a lot, thank you. I think I've found the bug - can you confirm if the messages not being deleted are replies (even some of them)?

**Comment by ghost** [comment]
> This helps a lot, thank you. I think I've found the bug - can you confirm if the messages not being deleted are replies (even some of them)?

It does seem all the left over messages are replies yes

**Comment by cedws** [comment]
Great, 1.4.2-hotfix1 has been released and should resolve this.
