### ISSUE TITLE
Add the ability to skip a channel category using its ID

### ISSUE THREAD

**Issue by PolicyPuma** [cedws/discord-delete#39]
Pretty much self explanatory. Would be very useful for myself.

Nice app BTW! Awesome work!

**Comment by cedws** [comment]
Could you clarify what you mean by *channel category*?

**Comment by lillelilje** [comment]
Categories are the topics that all channels are sorted within.

![image](https://user-images.githubusercontent.com/1491401/119051131-12cb3280-b9c3-11eb-9db0-9c9dc171fafc.png)
In this picture #general and #static is under the "WRITTEN CHIRPS" category. You can right click those to copy the ID, like any other channel.

With discord.py I believe you  can get a specific ID with:
category = get(guild.category_channels, name='WRITTEN CHIRPS') or something.

**Comment by cedws** [comment]
Unfortunately this isn't possible since Discord doesn't tell the client what category a message belongs to. It might be possible with some heavy logic but it would be too complex for a nice-to-have feature.
