### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by simplycontent** [cedws/discord-delete#6]
Hi!

I love the idea of this as i share your concerns about my data.

I have been on a discord server for quite many years now and as I am leaving it I wanted to delete a lot of old personal posts. I just installed this and gave it a try but it seems to me its not actually deleting anything, at least not on the server I am on.

I have had powershell open for a few hours now and it keeps posting lines like:

INFO:root:      - 518879316566867970
INFO:root:      - 518879285331886082
INFO:root:      - 518879261164306443

but when I search for my msgs or check history it doesnt seem like the total number of msgs posted (100k+) changes and the recent msgs I can find still seem to be there. As the script continues, it seems to do SOMETHING, is it fetching IDs to delete them at the end or should they be deleted 1 by 1?

Or is it fetching msgs from old servers I am no longer in and it hasnt even catched up and started with the main server I am currently in right now?

Does it matter if I have discord open in browser or the app while doing this, or that I answered a PM while script running? Would love some help or clarification and can provide with testing feedback. Do you have any discord you are on so I could get in touch with you via PM?

Thank you for your work!

Best regards,
Andy

**Comment by cedws** [comment]
The numbers you see printing out are message IDs that are being deleted. Try passing `-v` for verbose output; like `./discord-delete.py -v partial`.

This is a very good stress test, I guess you could say. I haven't ran the script at this kind of scale. It should be almost certainly deleting messages. Keep in mind that the Discord client caches messages, you might have to refresh/restart the client to see messages being deleted.

I've created an account you can contact me at: *removed*.
