### ISSUE TITLE
WARNING: Root: server sent Unauthorized.

### ISSUE THREAD

**Issue by Dman1245** [cedws/discord-delete#7]

**Comment by Dman1245** [comment]
![image](https://user-images.githubusercontent.com/48672033/54517292-8b835f80-491e-11e9-822f-e42da3099b23.png)

**Comment by cedws** [comment]
It's just a warning, so it can be ignored. That being said, I'm looking into an issue where some messages might not be deletable.

**Comment by Dman1245** [comment]
Sorry, I was just making a mistake.
